// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABYe_0XWqxZmZuUqfxITdoSIICn7Vgrvw',
    appId: '1:778468508118:web:94c1f8e903032437246477',
    messagingSenderId: '778468508118',
    projectId: 'eduquizsystem',
    authDomain: 'eduquizsystem.firebaseapp.com',
    storageBucket: 'eduquizsystem.firebasestorage.app',
    measurementId: 'G-8LL9VL13Y4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7nZatMkUrGavCG86s5cPU-1bqCnZwUO8',
    appId: '1:778468508118:android:62a35cb375995934246477',
    messagingSenderId: '778468508118',
    projectId: 'eduquizsystem',
    storageBucket: 'eduquizsystem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTCL5WtDofSwKI5yl37BKptJ9Q7EX91g4',
    appId: '1:778468508118:ios:3864eb9f65b75c37246477',
    messagingSenderId: '778468508118',
    projectId: 'eduquizsystem',
    storageBucket: 'eduquizsystem.firebasestorage.app',
    iosBundleId: 'com.example.eduQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABYe_0XWqxZmZuUqfxITdoSIICn7Vgrvw',
    appId: '1:778468508118:web:b2912cadda297c25246477',
    messagingSenderId: '778468508118',
    projectId: 'eduquizsystem',
    authDomain: 'eduquizsystem.firebaseapp.com',
    storageBucket: 'eduquizsystem.firebasestorage.app',
    measurementId: 'G-R0X7H1080G',
  );
}
